### ISSUE TITLE
MapPairsTest

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/diachromatic#150]
```
@Ignore("Broken because of new digest map.")
public class MapPairsTest 
```
can this be deleted? @hansenp

**Comment by hansenp** [comment]
I would have to take a closer look. Maybe the test can be repaired?

**Comment by pnrobinson** [comment]
there are no actual tests in the file and it is not used by any other code in the repo. Therefore, the file is obsolete/redundant -- deleting.
